# -*- coding: utf-8 -*-
"""LAB-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q28MnnteuCY_bXDv3-P_qv3YsZQhgmAH
"""

from google.colab import drive
import os
import pandas as pd
import zipfile

# 1. Mount your Google Drive
drive.mount('/content/drive')

# 2. Set the path to where your ZIP file is stored in Google Drive
ZIP_PATH = '/content/drive/MyDrive/Datasets/LAB-5/Brand Sentiment.zip'

# 3. Specify the name of the CSV file within the ZIP archive you want to load
CSV_FILE_IN_ZIP = 'Dataset - Train.csv' # Or 'Dataset - Test.csv' or 'Dataset Card.csv'

# 4. Load the specified CSV from the ZIP file into your Stage 1 pipeline
with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
    with zf.open(CSV_FILE_IN_ZIP) as f:
        raw = pd.read_csv(f)

print(f"Dataset '{CSV_FILE_IN_ZIP}' loaded successfully! Shape:", raw.shape)

!pip install -q vaderSentiment matplotlib seaborn scikit-learn pandas numpy

import os, re, joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.dummy import DummyClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, f1_score, confusion_matrix, ConfusionMatrixDisplay
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Reproducibility
SEED = 42
np.random.seed(SEED)
OUT = '/content/lab05_outputs'
os.makedirs(OUT, exist_ok=True)

# --- CONFIGURATION (EXACT MATCH FOR YOUR BRAND SENTIMENT DATASET) ---
TEXT_COL = 'tweet_text'
TARGET_COL = 'is_there_an_emotion_directed_at_a_brand_or_product'
ENTITY_COL = 'emotion_in_tweet_is_directed_at'
ID_COL = 'tweet_id'

# ==========================================
# 1. Dataset loading & ID Generation
# ==========================================
print("✅ 1. Dataset loading complete. Shape:", raw.shape)

# Create an ID column if missing
if ID_COL not in raw.columns:
    raw[ID_COL] = raw.index

# ==========================================
# 2. Data understanding/documentation
# ==========================================
print("\n✅ 2. Data understanding/documentation:")
print(raw.info())
print("\nTarget Class Distribution:\n", raw[TARGET_COL].value_counts(normalize=True))

# ==========================================
# 3. Data-quality checks
# ==========================================
print("\n✅ 3. Data-quality checks:")
missing_vals = raw[[TEXT_COL, TARGET_COL]].isna().sum()
print("Missing values in core columns:\n", missing_vals)

# ==========================================
# 4. Cleaning and duplicate/conflict handling
# ==========================================
# Drop nulls in required columns
df = raw.dropna(subset=[TEXT_COL, TARGET_COL]).copy()

# Deduplication (Drop exact duplicates of text)
initial_len = len(df)
df = df.drop_duplicates(subset=[TEXT_COL])
print(f"\n✅ 4. Cleaning complete. Dropped {initial_len - len(df)} duplicate texts.")

# Minimal Text Normalization (Lab 05 requirement)
def normalize_tweet(text):
    text = str(text)
    text = re.sub(r'https?://\S+|www\.\S+', ' <URL>', text)
    text = re.sub(r'@\w+', ' <USER>', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_text'] = df[TEXT_COL].map(normalize_tweet)
df['tweet_length'] = df['clean_text'].apply(lambda x: len(x.split()))

# ==========================================
# 5. EDA and visualizations
# ==========================================
print("\n✅ 5. EDA and visualizations generated.")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Target Distribution
sns.countplot(data=df, x=TARGET_COL, ax=axes[0], palette='viridis')
axes[0].set_title('Sentiment Class Distribution')
axes[0].tick_params(axis='x', rotation=30)

# Plot 2: Tweet Length by Sentiment
sns.boxplot(data=df, x=TARGET_COL, y='tweet_length', ax=axes[1], palette='viridis')
axes[1].set_title('Tweet Length Distribution by Sentiment')
axes[1].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.savefig(os.path.join(OUT, 'eda_plots.png'))
plt.show()

# ==========================================
# 6. Train/validation/test split
# ==========================================
train_df, test_df = train_test_split(
    df, test_size=0.20, random_state=SEED, stratify=df[TARGET_COL]
)
X_train, y_train = train_df['clean_text'], train_df[TARGET_COL]
X_test, y_test = test_df['clean_text'], test_df[TARGET_COL]
print(f"\n✅ 6. Train/test split complete. Train: {len(train_df)}, Test: {len(test_df)}")

# ==========================================
# 7. Leakage/overlap checks
# ==========================================
overlap = set(train_df.index).intersection(set(test_df.index))
assert len(overlap) == 0, "DATA LEAKAGE DETECTED: Overlap between train and test indices."
print("✅ 7. Leakage/overlap checks passed. No overlap detected.")

# ==========================================
# 8. Dummy baseline
# ==========================================
dummy = Pipeline([
    ('tfidf', TfidfVectorizer(min_df=2)),
    ('clf', DummyClassifier(strategy='most_frequent', random_state=SEED))
])
dummy.fit(X_train, y_train)
dummy_f1 = f1_score(y_test, dummy.predict(X_test), average='macro')
print(f"\n✅ 8. Dummy baseline Macro F1: {dummy_f1:.4f}")

# ==========================================
# 9. VADER baseline
# ==========================================
analyzer = SentimentIntensityAnalyzer()
def vader_label(text):
    c = analyzer.polarity_scores(text)['compound']
    if c >= 0.05: return 'Positive emotion'
    if c <= -0.05: return 'Negative emotion'
    return 'No emotion toward brand or product'

vader_pred = X_test.map(vader_label)
print("✅ 9. VADER baseline executed.")

# ==========================================
# 10 - 14. TF-IDF, Models, and 5-fold CV
# ==========================================
print("\n✅ 10-14. Running TF-IDF, Models (NB, LR, SVC), and 5-fold CV...")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

models = {
    'MultinomialNB': Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.98, sublinear_tf=True)),
        ('clf', MultinomialNB(alpha=0.5))
    ]),
    'LogisticRegression': Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.98, sublinear_tf=True)),
        ('clf', LogisticRegression(max_iter=2000, class_weight='balanced', random_state=SEED))
    ]),
    'LinearSVC': Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.98, sublinear_tf=True)),
        ('clf', LinearSVC(class_weight='balanced', random_state=SEED))
    ])
}

# ==========================================
# 15. Hyperparameter tuning (GridSearchCV)
# ==========================================
print("\n✅ 15. Performing Hyperparameter Tuning (GridSearchCV)...")
param_grid = {
    'tfidf__max_df': [0.90, 0.98],
    'clf__C': [0.1, 1.0, 10.0]
}
grid_search = GridSearchCV(
    models['LogisticRegression'],
    param_grid,
    cv=cv,
    scoring='f1_macro',
    n_jobs=-1
)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_
print(f"Best parameters found: {grid_search.best_params_}")

# ==========================================
# 16. Final test evaluation
# ==========================================
print("\n✅ 16. Final test evaluation (Locked Test Set):")
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred, digits=4))

# ==========================================
# 17. Confusion matrix
# ==========================================
print("\n✅ 17. Confusion matrix generated.")
cm = confusion_matrix(y_test, y_pred, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap='Blues', values_format='d')
plt.title('Final Model Confusion Matrix')
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig(os.path.join(OUT, 'confusion_matrix.png'))
plt.show()

# ==========================================
# 18. Error analysis
# ==========================================
print("\n✅ 18. Error analysis (Sample of misclassified tweets):")
test_results = test_df.copy()
test_results['prediction'] = y_pred
errors = test_results[test_results[TARGET_COL] != test_results['prediction']]

for idx, row in errors.head(5).iterrows():
    print(f"- True: {row[TARGET_COL]} | Pred: {row['prediction']}")
    print(f"  Text: {row[TEXT_COL][:150]}...\n")

# ==========================================
# 19. Entity-level analysis
# ==========================================
if ENTITY_COL in test_results.columns:
    print("\n✅ 19. Entity-level analysis:")
    # Filter non-null entities
    entity_df = test_results.dropna(subset=[ENTITY_COL])
    if not entity_df.empty:
        entity_summary = pd.crosstab(
            entity_df[ENTITY_COL], entity_df['prediction'], normalize='index'
        ).round(3)
        entity_summary['Total_Tweets'] = entity_df[ENTITY_COL].value_counts()
        print(entity_summary.head(10))
    else:
        print("No valid entities found in test set.")

# ==========================================
# 20. Model saving
# ==========================================
model_path = os.path.join(OUT, 'best_tuned_pipeline.joblib')
joblib.dump(best_model, model_path)
print(f"\n✅ 20. Model saved to {model_path}")

# ==========================================
# 21. Model reload verification
# ==========================================
reloaded_model = joblib.load(model_path)
predictions_match = np.array_equal(
    reloaded_model.predict(X_test.iloc[:50]),
    best_model.predict(X_test.iloc[:50])
)
print(f"✅ 21. Model reload verification — both returned True: {predictions_match}")

# 0. Install required package (if running in a fresh runtime)
!pip install -q vaderSentiment

# 1. Imports and Setup
from google.colab import drive
import os, re, joblib, zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.dummy import DummyClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, f1_score, confusion_matrix, ConfusionMatrixDisplay
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

SEED = 42
np.random.seed(SEED)
OUT = '/content/lab05_dataset2_outputs'
os.makedirs(OUT, exist_ok=True)

# ==========================================
# 1. Dataset loading (Configured for Twitter Entity Dataset)
# ==========================================
# ⚠️ Ensure this path points to your dataset 2 ZIP or CSV in Drive
drive.mount('/content/drive')
ZIP_PATH = '/content/drive/MyDrive/Datasets/LAB-5/Twitter.zip'
CSV_FILE_IN_ZIP = 'twitter_training.csv'

# Explicitly defining column names since this Kaggle dataset lacks headers
COL_NAMES = ['tweet_id', 'entity', 'sentiment', 'tweet_text']

with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
    with zf.open(CSV_FILE_IN_ZIP) as f:
        raw = pd.read_csv(f, names=COL_NAMES, header=None)

print(f"✅ 1. Dataset loading complete. Shape: {raw.shape}")

# --- CONFIGURATION FOR DATASET 2 ---
TEXT_COL = 'tweet_text'
TARGET_COL = 'sentiment'
ENTITY_COL = 'entity'
ID_COL = 'tweet_id'

# ==========================================
# 2. Data understanding/documentation
# ==========================================
print("\n✅ 2. Data understanding/documentation:")
print(raw.info())
print("\nTarget Class Distribution (Raw):\n", raw[TARGET_COL].value_counts(normalize=True))

# ==========================================
# 3 & 4. Data-quality checks & Cleaning
# ==========================================
print("\n✅ 3 & 4. Quality checks and Cleaning:")
missing_vals = raw[[TEXT_COL, TARGET_COL]].isna().sum()
print("Missing values before drop:\n", missing_vals)

# Drop nulls
df = raw.dropna(subset=[TEXT_COL, TARGET_COL]).copy()

# Filter out 'Irrelevant' to keep the standard 3-class sentiment task
initial_len = len(df)
df = df[df[TARGET_COL] != 'Irrelevant'].copy()
print(f"Dropped {initial_len - len(df)} 'Irrelevant' rows to maintain 3-class structure.")

# Deduplication
initial_len = len(df)
df = df.drop_duplicates(subset=[TEXT_COL])
print(f"Dropped {initial_len - len(df)} duplicate texts.")

# Minimal Text Normalization
def normalize_tweet(text):
    text = str(text)
    text = re.sub(r'https?://\S+|www\.\S+', ' <URL>', text)
    text = re.sub(r'@\w+', ' <USER>', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_text'] = df[TEXT_COL].map(normalize_tweet)
df['tweet_length'] = df['clean_text'].apply(lambda x: len(x.split()))

# ==========================================
# 5. EDA and visualizations
# ==========================================
print("\n✅ 5. EDA and visualizations generated.")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.countplot(data=df, x=TARGET_COL, ax=axes[0], palette='viridis')
axes[0].set_title('Sentiment Class Distribution')

sns.boxplot(data=df, x=TARGET_COL, y='tweet_length', ax=axes[1], palette='viridis')
axes[1].set_title('Tweet Length Distribution by Sentiment')

plt.tight_layout()
plt.savefig(os.path.join(OUT, 'eda_plots_ds2.png'))
plt.show()

# ==========================================
# 6 & 7. Frozen Split & Leakage Checks
# ==========================================
train_df, test_df = train_test_split(
    df, test_size=0.20, random_state=SEED, stratify=df[TARGET_COL]
)
X_train, y_train = train_df['clean_text'], train_df[TARGET_COL]
X_test, y_test = test_df['clean_text'], test_df[TARGET_COL]
print(f"\n✅ 6. Train/test split complete. Train: {len(train_df)}, Test: {len(test_df)}")

overlap = set(train_df.index).intersection(set(test_df.index))
assert len(overlap) == 0, "DATA LEAKAGE DETECTED: Overlap between train and test indices."
print("✅ 7. Leakage/overlap checks passed.")

# ==========================================
# 8 & 9. Dummy and VADER baselines
# ==========================================
dummy = Pipeline([
    ('tfidf', TfidfVectorizer(min_df=2)),
    ('clf', DummyClassifier(strategy='most_frequent', random_state=SEED))
])
dummy.fit(X_train, y_train)
dummy_f1 = f1_score(y_test, dummy.predict(X_test), average='macro')
print(f"\n✅ 8. Dummy baseline Macro F1: {dummy_f1:.4f}")

analyzer = SentimentIntensityAnalyzer()
def vader_label(text):
    c = analyzer.polarity_scores(text)['compound']
    if c >= 0.05: return 'Positive'
    if c <= -0.05: return 'Negative'
    return 'Neutral'

vader_pred = X_test.map(vader_label)
vader_f1 = f1_score(y_test, vader_pred, average='macro')
print(f"✅ 9. VADER baseline Macro F1: {vader_f1:.4f}")

# ==========================================
# 10 - 14. TF-IDF, Models, and 5-fold CV
# ==========================================
print("\n✅ 10-14. Running TF-IDF, Models (NB, LR, SVC), and 5-fold CV...")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

models = {
    'MultinomialNB': Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.98, sublinear_tf=True)),
        ('clf', MultinomialNB(alpha=0.5))
    ]),
    'LogisticRegression': Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.98, sublinear_tf=True)),
        ('clf', LogisticRegression(max_iter=2000, class_weight='balanced', random_state=SEED))
    ]),
    'LinearSVC': Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2, max_df=0.98, sublinear_tf=True)),
        ('clf', LinearSVC(class_weight='balanced', random_state=SEED))
    ])
}

# ==========================================
# 15. Hyperparameter tuning (GridSearchCV)
# ==========================================
print("\n✅ 15. Performing Hyperparameter Tuning (LinearSVC)...")
# Tuning LinearSVC since it's typically the strongest on this specific Kaggle dataset
param_grid = {
    'tfidf__max_df': [0.90, 0.98],
    'clf__C': [0.1, 1.0]
}
grid_search = GridSearchCV(
    models['LinearSVC'],
    param_grid,
    cv=cv,
    scoring='f1_macro',
    n_jobs=-1
)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_
print(f"Best parameters found: {grid_search.best_params_}")

# ==========================================
# 16 & 17. Final evaluation and Confusion matrix
# ==========================================
print("\n✅ 16. Final test evaluation (Locked Test Set):")
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred, digits=4))

print("\n✅ 17. Confusion matrix generated.")
cm = confusion_matrix(y_test, y_pred, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap='Blues', values_format='d')
plt.title('Final Model Confusion Matrix (Dataset 2)')
plt.savefig(os.path.join(OUT, 'confusion_matrix_ds2.png'))
plt.show()

# ==========================================
# 18. Error analysis
# ==========================================
print("\n✅ 18. Error analysis (Sample of misclassified tweets):")
test_results = test_df.copy()
test_results['prediction'] = y_pred
errors = test_results[test_results[TARGET_COL] != test_results['prediction']]

for idx, row in errors.head(5).iterrows():
    print(f"- True: {row[TARGET_COL]} | Pred: {row['prediction']}")
    print(f"  Text: {row[TEXT_COL][:150]}...\n")

# ==========================================
# 19. Entity-level analysis
# ==========================================
if ENTITY_COL in test_results.columns:
    print("\n✅ 19. Entity-level analysis:")
    entity_df = test_results.dropna(subset=[ENTITY_COL])
    if not entity_df.empty:
        # Cross-tabulate and print top 10 entities
        entity_summary = pd.crosstab(
            entity_df[ENTITY_COL], entity_df['prediction'], normalize='index'
        ).round(3)
        entity_summary['Total_Tweets'] = entity_df[ENTITY_COL].value_counts()

        # Sort by total tweets to analyze the most discussed entities
        entity_summary = entity_summary.sort_values(by='Total_Tweets', ascending=False)

        # Presenting data cleanly
        print(entity_summary.head(10).to_string())
    else:
        print("No valid entities found in test set.")

# ==========================================
# 20 & 21. Model saving and Reload verification
# ==========================================
model_path = os.path.join(OUT, 'best_tuned_pipeline_ds2.joblib')
joblib.dump(best_model, model_path)
print(f"\n✅ 20. Model saved to {model_path}")

reloaded_model = joblib.load(model_path)
predictions_match = np.array_equal(
    reloaded_model.predict(X_test.iloc[:50]),
    best_model.predict(X_test.iloc[:50])
)
print(f"✅ 21. Model reload verification — both returned True: {predictions_match}")

from datetime import datetime

def generate_dataset_card(raw_df, clean_df, train_df, test_df, target_col):
    """
    Generates the Required Dataset Card as specified in MDI3003 Lab 05 Manual.
    Update the qualitative string variables below to match your specific dataset.
    """

    # --- QUALITATIVE METADATA (Update these based on your specific dataset) ---
    dataset_name = "Twitter Entity Sentiment Analysis" # Or "Brand Sentiment Analysis"
    source_url = "https://www.kaggle.com/datasets/jp797498e/twitter-entity-sentiment-analysis"
    access_date = datetime.now().strftime("%B %d, %Y")
    license_terms = "Public/Kaggle (Verify specific CC license on source page)"
    language_domain = "English; Social Media (Twitter/X) gaming, brand, and entity discourse"
    annotation_method = "Human annotation (likely contains moderate label noise due to subjective interpretation of sarcasm/context)"
    excluded_fields = "Usernames, locations, and Tweet IDs excluded to prevent data leakage and protect PII"
    sampling_limitations = "Twitter demographics do not represent the full customer population. Data is subject to temporal drift and platform-specific language trends."

    # --- CALCULATED METADATA ---
    raw_rows = len(raw_df)
    clean_rows = len(clean_df)
    duplicates_removed = raw_rows - clean_rows

    label_dist = clean_df[target_col].value_counts().to_dict()
    label_dist_str = ", ".join([f"{k}: {v}" for k, v in label_dist.items()])

    # --- PRINT DATASET CARD ---
    print("="*70)
    print(" 📄 MDI3003 LAB 05 - REQUIRED DATASET CARD")
    print("="*70)
    print(f"• Dataset name and canonical/public source:\n  {dataset_name}\n  {source_url}\n")
    print(f"• Version/access date and license/usage note:\n  Accessed on: {access_date}\n  License: {license_terms}\n")
    print(f"• Number of rows and label distribution:\n  Total Rows (After Cleaning): {clean_rows}\n  Distribution: {label_dist_str}\n")
    print(f"• Train/validation/test definition:\n  80/20 Stratified Split (Locked test set)\n  Training rows: {len(train_df)}\n  Testing rows: {len(test_df)}\n")
    print(f"• Duplicate and near-duplicate policy:\n  Exact duplicate text rows dropped.\n  Total duplicates removed: {duplicates_removed}\n")
    print(f"• Language and domain:\n  {language_domain}\n")
    print(f"• Annotation method and likely label noise:\n  {annotation_method}\n")
    print(f"• Fields excluded for privacy or leakage:\n  {excluded_fields}\n")
    print(f"• Known sampling limitations and temporal coverage:\n  {sampling_limitations}")
    print("="*70)

# Execute the function using the DataFrames generated in earlier steps
generate_dataset_card(
    raw_df=raw,
    clean_df=df,
    train_df=train_df,
    test_df=test_df,
    target_col=TARGET_COL
)

import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_validate # Ensure cross_validate is imported

def generate_manual_result_tables(best_model, X_test, y_test, y_pred, cv_results_df, test_df, entity_col='brand_name'):
    """
    Generates the exact result tables required by Section 20 of the Lab 05 Manual.
    """
    print("\n" + "="*60)
    print(" 📋 REQUIRED RESULT-TABLE TEMPLATES (SECTION 20)")
    print("="*60 + "\n")

    # ---------------------------------------------------------
    # TABLE 1: Model Comparison (CV Results)
    # ---------------------------------------------------------
    print("--- TABLE 1: MODEL COMPARISON (CV) ---")
    if cv_results_df is not None and not cv_results_df.empty:
        # Rename columns to match the manual's template
        table1 = cv_results_df.copy()

        # Add a dummy representation column based on the model name
        table1['Representation'] = table1['model'].apply(
            lambda x: 'Word TF-IDF (1,2)' if x != 'VADER' else 'Lexicon/Rules'
        )

        table1 = table1[['model', 'Representation', 'macro_f1_mean', 'macro_f1_sd', 'weighted_f1_mean', 'fit_time_mean']]
        table1.columns = ['Model', 'Representation', 'CV macro F1 mean', 'CV macro F1 SD', 'Weighted F1', 'Fit time (s)']

        print(table1.round(4).to_string(index=False))
        table1.to_csv(os.path.join(OUT, 'Table1_Model_Comparison.csv'), index=False)
    else:
        print("CV Results DataFrame not provided.")
    print("\n")

    # ---------------------------------------------------------
    # TABLE 2: Class Metrics & Confusions
    # ---------------------------------------------------------
    print("--- TABLE 2: CLASS METRICS & CONFUSIONS ---")
    classes = best_model.classes_
    report = classification_report(y_test, y_pred, output_dict=True, labels=classes)
    cm = confusion_matrix(y_test, y_pred, labels=classes)

    class_rows = []
    for i, cls_name in enumerate(classes):
        # Find the most common confusion (highest predicted class that is NOT the true class)
        row_confusions = cm[i].copy()
        row_confusions[i] = -1 # Ignore correct predictions
        most_confused_idx = np.argmax(row_confusions)

        if row_confusions[most_confused_idx] > 0:
            most_common_confusion = f"Predicted as {classes[most_confused_idx]} ({row_confusions[most_confused_idx]} times)"
        else:
            most_common_confusion = "None"

        class_rows.append({
            'Class': cls_name,
            'Precision': report[cls_name]['precision'],
            'Recall': report[cls_name]['recall'],
            'F1': report[cls_name]['f1-score'],
            'Support': int(report[cls_name]['support']),
            'Most common confusion': most_common_confusion
        })

    table2 = pd.DataFrame(class_rows)
    print(table2.round(4).to_string(index=False))
    table2.to_csv(os.path.join(OUT, 'Table2_Class_Metrics.csv'), index=False)
    print("\n")

    # ---------------------------------------------------------
    # TABLE 3: Entity/Product Analysis
    # ---------------------------------------------------------
    if entity_col in test_df.columns:
        print("--- TABLE 3: ENTITY/PRODUCT ANALYSIS (Min Support 30) ---")
        MIN_SUPPORT = 30

        test_with_preds = test_df.copy()
        test_with_preds['prediction'] = y_pred

        # Filter entities by minimum support
        entity_counts = test_with_preds[entity_col].value_counts()
        valid_entities = entity_counts[entity_counts >= MIN_SUPPORT].index

        if len(valid_entities) > 0:
            filtered_df = test_with_preds[test_with_preds[entity_col].isin(valid_entities)]

            # Calculate percentages
            table3 = pd.crosstab(
                filtered_df[entity_col], filtered_df['prediction'], normalize='index'
            ) * 100

            # Add Support (N)
            table3.insert(0, 'N tweets', filtered_df[entity_col].value_counts())

            # Add a 'Key Caution' column (manual requirement)
            table3['Key caution'] = "Do not overinterpret; social media is not a full market sample."

            # Rename columns to ensure % Neg, % Neutral, % Pos exist if possible
            # Note: Column names depend on your exact dataset labels.
            table3 = table3.round(1)
            print(table3.head(10).to_string())
            table3.to_csv(os.path.join(OUT, 'Table3_Entity_Analysis.csv'))
        else:
            print(f"No entities met the minimum support threshold of {MIN_SUPPORT}.")
    else:
        print(f"Entity column '{entity_col}' not found in test data.")
    print("="*60)

# ==========================================
# Generate cv_results for this dataset
# (This code was previously in a different cell for Dataset 1)
# ==========================================
print("\n--- Generating CV Results for Table 1 ---")
rows = []
for name, pipe in models.items():
    scores = cross_validate(
        pipe, X_train, y_train, cv=cv,
        scoring={'macro_f1': 'f1_macro', 'weighted_f1': 'f1_weighted', 'accuracy': 'accuracy'},
        n_jobs=-1, return_train_score=False
    )
    rows.append({
        'model': name,
        'macro_f1_mean': scores['test_macro_f1'].mean(),
        'macro_f1_sd': scores['test_macro_f1'].std(),
        'weighted_f1_mean': scores['test_weighted_f1'].mean(),
        'fit_time_mean': scores['fit_time'].mean() # 'fit_time' is returned automatically, no need to pass it in scoring
    })

cv_results = pd.DataFrame(rows).sort_values('macro_f1_mean', ascending=False)
print("CV Results DataFrame created successfully.")

# ==========================================
# Execute the table generator
# ==========================================
# Make sure you pass the correct entity column name for your dataset
# For Dataset 1 (Brand Sentiment): entity_col = 'emotion_in_tweet_is_directed_at'
# For Dataset 2 (Twitter Entity): entity_col = 'entity'

generate_manual_result_tables(
    best_model=best_model,
    X_test=X_test,
    y_test=y_test,
    y_pred=y_pred,
    cv_results_df=cv_results, # Now 'cv_results' is defined
    test_df=test_df,
    entity_col=ENTITY_COL
)

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

# Ensure output directory exists
OUT_VIZ = '/content/lab05_visualizations'
os.makedirs(OUT_VIZ, exist_ok=True)

def generate_all_visualizations(train_df, test_df, cv_results, best_model, text_col, target_col, entity_col):
    print("Generating Lab 05 Mandatory Visualizations...")

    classes = np.unique(train_df[target_col])

    # Ensure tweet length is calculated
    train_df['tweet_length'] = train_df[text_col].astype(str).apply(lambda x: len(x.split()))

    # ---------------------------------------------------------
    # 1 & 2. Class Distribution & Tweet-Length Distribution
    # ---------------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    sns.countplot(data=train_df, x=target_col, ax=axes[0], palette='viridis', order=classes)
    axes[0].set_title('1. Class Distribution (Training Data)')
    axes[0].tick_params(axis='x', rotation=30)

    sns.boxplot(data=train_df, x=target_col, y='tweet_length', ax=axes[1], palette='viridis', order=classes)
    axes[1].set_title('2. Tweet-Length Distribution by Class')
    axes[1].tick_params(axis='x', rotation=30)

    plt.tight_layout()
    plt.savefig(os.path.join(OUT_VIZ, '1_2_class_length_dist.png'))
    plt.show()

    # ---------------------------------------------------------
    # 3. Top terms or n-grams by class (Training data only)
    # ---------------------------------------------------------
    fig, axes = plt.subplots(1, len(classes), figsize=(5 * len(classes), 5))
    vec = CountVectorizer(stop_words='english', ngram_range=(1, 2), max_features=10)

    for i, cls in enumerate(classes):
        cls_text = train_df[train_df[target_col] == cls][text_col]
        if len(cls_text) > 0:
            term_matrix = vec.fit_transform(cls_text)
            term_sums = term_matrix.sum(axis=0).A1
            terms = vec.get_feature_names_out()

            # Sort by frequency
            sorted_idx = term_sums.argsort()[::-1]
            top_terms = terms[sorted_idx]
            top_counts = term_sums[sorted_idx]

            sns.barplot(x=top_counts, y=top_terms, ax=axes[i], palette='magma')
            axes[i].set_title(f'Top Terms: {cls}')
            axes[i].set_xlabel('Frequency')

    plt.suptitle('3. Top Terms/N-grams by Class (Training Data)', y=1.05)
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_VIZ, '3_top_terms.png'))
    plt.show()

    # ---------------------------------------------------------
    # 4. Cross-validation model-comparison plot
    # ---------------------------------------------------------
    if cv_results is not None and not cv_results.empty:
        plt.figure(figsize=(8, 5))
        sns.barplot(
            data=cv_results,
            x='model',
            y='macro_f1_mean',
            palette='Blues_r',
            capsize=0.1
        )
        # Adding error bars manually for standard deviation
        plt.errorbar(
            x=range(len(cv_results)),
            y=cv_results['macro_f1_mean'],
            yerr=cv_results['macro_f1_sd'],
            fmt='none', c='black'
        )
        plt.title('4. Cross-Validation Model Comparison (Macro F1 ± SD)')
        plt.ylim(0, 1.0)
        plt.tight_layout()
        plt.savefig(os.path.join(OUT_VIZ, '4_cv_comparison.png'))
        plt.show()

    # ---------------------------------------------------------
    # 5 & 6. Count and Row-Normalized Confusion Matrices
    # ---------------------------------------------------------
    y_test = test_df[target_col]
    y_pred = test_df['prediction']

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # 5. Count Confusion Matrix
    cm_raw = confusion_matrix(y_test, y_pred, labels=classes)
    disp_raw = ConfusionMatrixDisplay(confusion_matrix=cm_raw, display_labels=classes)
    disp_raw.plot(ax=axes[0], cmap='Blues', values_format='d')
    axes[0].set_title('5. Count Confusion Matrix')
    axes[0].tick_params(axis='x', rotation=30)

    # 6. Row-Normalized Confusion Matrix
    cm_norm = confusion_matrix(y_test, y_pred, labels=classes, normalize='true')
    disp_norm = ConfusionMatrixDisplay(confusion_matrix=cm_norm, display_labels=classes)
    disp_norm.plot(ax=axes[1], cmap='Blues', values_format='.2f')
    axes[1].set_title('6. Row-Normalized Confusion Matrix')
    axes[1].tick_params(axis='x', rotation=30)

    plt.tight_layout()
    plt.savefig(os.path.join(OUT_VIZ, '5_6_confusion_matrices.png'))
    plt.show()

    # ---------------------------------------------------------
    # 7. Per-class precision/recall/F1 plot
    # ---------------------------------------------------------
    report = classification_report(y_test, y_pred, output_dict=True, labels=classes)
    metrics_df = pd.DataFrame({
        'Class': np.repeat(classes, 3),
        'Metric': ['Precision', 'Recall', 'F1-Score'] * len(classes),
        'Score': [report[c][m] for c in classes for m in ['precision', 'recall', 'f1-score']]
    })

    plt.figure(figsize=(10, 5))
    sns.barplot(data=metrics_df, x='Class', y='Score', hue='Metric', palette='Set2')
    plt.title('7. Per-Class Precision, Recall, and F1-Score')
    plt.ylim(0, 1.1)
    plt.legend(loc='lower right')
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_VIZ, '7_per_class_metrics.png'))
    plt.show()

    # ---------------------------------------------------------
    # 8 & 9. Entity/Product Analysis (Sentiment Dist & Error Rate)
    # ---------------------------------------------------------
    if entity_col in test_df.columns:
        MIN_SUPPORT = 30
        entity_counts = test_df[entity_col].value_counts()
        valid_entities = entity_counts[entity_counts >= MIN_SUPPORT].index

        if len(valid_entities) > 0:
            filtered_df = test_df[test_df[entity_col].isin(valid_entities)].copy()
            filtered_df['is_error'] = filtered_df[target_col] != filtered_df['prediction']

            fig, axes = plt.subplots(2, 1, figsize=(12, 12))

            # 8. Entity Sentiment Distribution
            sentiment_dist = pd.crosstab(filtered_df[entity_col], filtered_df['prediction'], normalize='index')
            sentiment_dist.plot(kind='bar', stacked=True, ax=axes[0], colormap='viridis')
            axes[0].set_title(f'8. Predicted Sentiment Distribution by Entity (Min Support {MIN_SUPPORT})')
            axes[0].set_ylabel('Proportion')
            axes[0].tick_params(axis='x', rotation=45)
            axes[0].legend(title='Predicted Sentiment', bbox_to_anchor=(1.05, 1), loc='upper left')

            # 9. Error-rate by entity
            error_rates = filtered_df.groupby(entity_col)['is_error'].mean().sort_values(ascending=False)
            sns.barplot(x=error_rates.index, y=error_rates.values, ax=axes[1], palette='Reds_r')
            axes[1].set_title(f'9. Error Rate by Entity (Min Support {MIN_SUPPORT})')
            axes[1].set_ylabel('Error Rate')
            axes[1].tick_params(axis='x', rotation=45)

            plt.tight_layout()
            plt.savefig(os.path.join(OUT_VIZ, '8_9_entity_analysis.png'))
            plt.show()
        else:
            print(f"Skipping Plots 8 & 9: No entities met the minimum support of {MIN_SUPPORT}.")
    else:
        print(f"Skipping Plots 8 & 9: Entity column '{entity_col}' not found.")

# ==========================================
# Execution Command
# ==========================================
# Make sure test_df contains your predictions before running this!
if 'prediction' not in test_df.columns:
    test_df['prediction'] = best_model.predict(test_df['clean_text'])

# Pass the appropriate variables for your dataset
generate_all_visualizations(
    train_df=train_df,
    test_df=test_df,
    cv_results=cv_results,
    best_model=best_model,
    text_col=TEXT_COL,
    target_col=TARGET_COL,
    entity_col=ENTITY_COL
)

import pandas as pd
import os

def generate_dataset_metadata_table(raw_ds1, raw_ds2):
    """
    Generates the Dataset Metadata Table template for Section 20.
    """
    print("\n========================================================")
    print(" 📋 DATASET METADATA TABLE (SECTION 20)")
    print("========================================================\n")

    # Define the metadata for both datasets
    # Note: Rows are dynamically calculated from your loaded 'raw' DataFrames
    metadata = [
        {
            "Dataset": "Brand Sentiment Analysis",
            "Source/version": "Kaggle (tusharpaul2001)",
            "Rows": len(raw_ds1) if raw_ds1 is not None else 8589,
            "Classes": "3 (Positive, Negative, Neutral)",
            "Split": "80/20 Stratified",
            "License/terms": "Kaggle Public",
            "Primary domain": "Brand/Product discourse"
        },
        {
            "Dataset": "Twitter Entity Sentiment",
            "Source/version": "Kaggle (jp797498e)",
            "Rows": len(raw_ds2) if raw_ds2 is not None else "Dynamic",
            "Classes": "3 (Positive, Negative, Neutral)",
            "Split": "80/20 Stratified",
            "License/terms": "Kaggle Public",
            "Primary domain": "Entity/Gaming/Brand discourse"
        }
    ]

    # Create the DataFrame
    metadata_df = pd.DataFrame(metadata)

    # Print the output clearly to the console
    print(metadata_df.to_string(index=False))

    # Save the output to a CSV file for your final submission
    out_dir = '/content/lab05_outputs'
    os.makedirs(out_dir, exist_ok=True)
    output_path = os.path.join(out_dir, 'Dataset_Metadata_Table.csv')
    metadata_df.to_csv(output_path, index=False)

    print(f"\n✅ Dataset metadata table saved to {output_path}")

    return metadata_df

# ==========================================
# Execution Command
# ==========================================
# Assuming 'raw' is your loaded Brand Sentiment dataframe
# and 'raw_ds2' is your loaded Twitter Entity dataframe.
# If you are running these in separate notebooks, you can pass None for the other dataset
# and manually update the hardcoded row count.

dataset_metadata_table = generate_dataset_metadata_table(
    raw_ds1=raw,       # Replace with your actual Dataset 1 variable
    raw_ds2=None       # Replace with your actual Dataset 2 variable if loaded, else None
)